Repository 7nohe/openapi-react-query-codegen, pull requests merged in 2024-04, with the labels that each got.

#60 fix(query): add default parameter initializer
  examples/react-app/src/App.tsx
  src/createUseQuery.mts
Labels: enhancement

#61 fix(exports): strip referenced imports of models
  src/createUseQuery.mts
Labels: bug

#67 Warn if no models, instead of throwing an error
  src/createImports.mts
Labels: bug

#69 fix: allow initialData
  src/createUseQuery.mts
Labels: enhancement

#73 fix(enums): take in and pass correct values to service generator
  README.md
  src/cli.mts
  src/generate.mts
Labels: bug

#93 ci: add prelease comment trigger
  .github/workflows/comment-release.yml
Labels: enhancement

#88 chore(docs): Update README.md of CLI commands and add info
  README.md
Labels: documentation

#92 feat(prefetch): add prefetch query hook generation
  README.md
  examples/react-app/src/main.tsx
  src/constants.mts
  src/createExports.mts
  src/createPrefetch.mts
  src/createSource.mts
  src/createUseQuery.mts
  tests/__snapshots__/createSource.test.ts.snap
  tests/__snapshots__/generate.test.ts.snap
  tests/createSource.test.ts
  tests/generate.test.ts
Labels: enhancement

#101 Update README.md
  README.md
Labels: documentation

#99 ci: update comment-release workflow
  .github/workflows/comment-release.yml
Labels: bug, help wanted

#98 fix(cli): set serviceResponse default value to body
  README.md
  src/cli.mts
Labels: bug

#97 feat: add query key function
  README.md
  examples/react-app/src/App.tsx
  src/common.mts
  src/createExports.mts
  src/createUseQuery.mts
  tests/__snapshots__/createSource.test.ts.snap
  tests/__snapshots__/generate.test.ts.snap
  tests/createExports.test.ts
Labels: enhancement
